Bug #39: Fix d2lbook translate
d2lbook translate was failing due to merge conflicts if src repo already exists with the following error:
```
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v origin
```
See #39 for more info..